services:
  letta-db:
    image: pgvector/pgvector:pg18-trixie
    container_name: letta-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: letta
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: letta
    volumes:
      - pgsql:/var/lib/postgresql
      - ./letta/database:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U letta" ]
      interval: 300s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 2s
  letta-git:
    build: ./letta/git
    container_name: letta-git
    restart: unless-stopped
    ports: [ "8285:8285" ]
    volumes:
      - config:/root/.letta
    healthcheck:
      test: [ "CMD-SHELL", "curl -s http://localhost:8285 || [ $? -eq 22 ] || [ $? -eq 0 ]" ]
      interval: 300s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 2s
  letta:
    image: letta/letta:latest
    container_name: letta
    restart: unless-stopped
    ports: [ "8283:8283" ]
    volumes:
      - config:/root/.letta
    environment:
      - LETTA_PG_URI=postgresql://letta:${DB_PASSWORD}@letta-db:5432/letta
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - LETTA_MEMFS_SERVICE_URL=http://letta-git:8285
      - SECURE=true 
      - LETTA_SERVER_PASSWORD=${LETTA_PASSWORD}
    depends_on:
      letta-git:
        condition: service_healthy
      letta-db:
        condition: service_healthy
volumes:
  pgsql:
  config:
